/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerHome: typeof import('./components/home/banner/BannerHome.vue')['default']
    BannerHomeDesktop: typeof import('./components/home/banner/desktop/BannerHomeDesktop.vue')['default']
    BannerHomeMobile: typeof import('./components/home/banner/mobile/BannerHomeMobile.vue')['default']
    HeaderDesktop: typeof import('./components/global/header/HeaderDesktop.vue')['default']
    HeaderMobile: typeof import('./components/global/header/HeaderMobile.vue')['default']
    LayoutDesktop: typeof import('./components/layouts/LayoutDesktop.vue')['default']
    LayoutMobile: typeof import('./components/layouts/LayoutMobile.vue')['default']
    NearbyParking: typeof import('./components/global/card/NearbyParking.vue')['default']
    NearbyParkingSection: typeof import('./components/home/NearbyParkingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserTypeCard: typeof import('./components/auth/userType/userTypeCard/UserTypeCard.vue')['default']
    UserTypeCardDesktop: typeof import('./components/auth/userType/userTypeCard/desktop/UserTypeCardDesktop.vue')['default']
    UserTypeCardMobile: typeof import('./components/auth/userType/userTypeCard/mobile/UserTypeCardMobile.vue')['default']
  }
}
