/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BannerHomeLarge: typeof import('./components/templates/large/home/BannerHomeLarge.vue')['default']
    BannerHomeSmall: typeof import('./components/templates/small/home/BannerHomeSmall.vue')['default']
    HeaderLarge: typeof import('./components/templates/large/HeaderLarge.vue')['default']
    HeaderSmall: typeof import('./components/templates/small/HeaderSmall.vue')['default']
    LayoutLarge: typeof import('./components/layouts/LayoutLarge.vue')['default']
    LayoutSmall: typeof import('./components/layouts/LayoutSmall.vue')['default']
    MenuSmall: typeof import('./components/small/MenuSmall.vue')['default']
    NearbyParking: typeof import('./components/global/card/NearbyParking.vue')['default']
    NearbyParkingSection: typeof import('./components/home/NearbyParkingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
